### ISSUE TITLE
Performance not match

### ISSUE THREAD

**Issue by Wangt-CN** [open-mmlab/mmclassification#24]
Hi, thanks for your work.

I have just download the pre-trained model ([ResNet18](https://openmmlab.oss-accelerate.aliyuncs.com/mmclassification/v0/imagenet/resnet18_batch256_20200708-34ab8f90.pth)) in model zoo. 
However, the performance on val set is actually **69.28** (top-1) with 4 GPUs. It's not matched with your log file.

I am very confused.
Thanks a lot.

**Comment by Wangt-CN** [comment]
![image](https://user-images.githubusercontent.com/32795963/89293089-ee020a80-d68f-11ea-913f-e228980ddd83.png)

**Comment by yl-1993** [comment]
@Wangt-CN Thanks for reporting the issue. I have tried the pretrained model and the performance is the same as your reported results. The reason is probably due to the inconsistent `resize` between training and testing, which will be fixed according to PR https://github.com/open-mmlab/mmclassification/pull/22.
