### ISSUE TITLE
为什么自己训练的 Resnet50 模型是204.8MB， 而官方提供的模型大小是 102.5MB？

### ISSUE THREAD

**Issue by jacob081** [open-mmlab/mmclassification#412]
RT

**Comment by mzr1996** [comment]
Hello, usually in your checkpoint, some extra information is saved, for example, the optimizer information. They are for resuming training.
Before publishing checkpoints, we will delete them. Refers to the `tools/model_converters/publish_model.py`
In addition, if you set a larger `num_classes`, the model size will also be larger because of a larger linear layer.

**Comment by jacob081** [comment]
@mzr1996 Thank you for your prompt reply. I have solved this problem.
