### ISSUE TITLE
构建dataset

### ISSUE THREAD

**Issue by dugudongfangshuo** [open-mmlab/mmclassification#420]
info = dict(
                img_prefix=self.data_prefix,
                img_info=dict(filename=filename),
                gt_label=gt_label.astype(np.int8))

这里的img_info ，img_prefix在哪里解析的 我看base_dataset里面没有关于这两个字段的解析读取操作呀

**Comment by Ezra-Yu** [comment]
没有理解你的问题，你给出的位置，也就是[定义的数据集的load_annotations函数中](https://github.com/open-mmlab/mmclassification/blob/0184527bd4f858f00be587f42979212c6a0ef32a/mmcls/datasets/imagenet.py#L1099)就是解析的代码。

data_prefix在config文件中制定，[构造Dataset](https://github.com/open-mmlab/mmclassification/blob/0184527bd4f858f00be587f42979212c6a0ef32a/mmcls/datasets/base_dataset.py#L30)时传入

img_info是一张图片的信息，这里只放filename， filename在self.sample中，由[get_sample](https://github.com/open-mmlab/mmclassification/blob/0184527bd4f858f00be587f42979212c6a0ef32a/mmcls/datasets/imagenet.py#L1079)函数得到

**Comment by mzr1996** [comment]
Hello, please use English or Chinese & English to open an issue in the future, so that your issue can help more people.

According to my understanding, you're wondering about where `img_prefix` and `img_info` are used.

At first, please read the docs about our [data pipeline](https://mmclassification.readthedocs.io/zh_CN/latest/tutorials/data_pipeline.html#id2), and we use data pipelines to process each data info dict.

In `LoadImageFromFile`, we parse `img_prefix` and `img_info` and get the image path to load.
https://github.com/open-mmlab/mmclassification/blob/0184527bd4f858f00be587f42979212c6a0ef32a/mmcls/datasets/pipelines/loading.py#L10-L63

**Comment by dugudongfangshuo** [comment]
thank you i find LoadImageFromFile

**Comment by dugudongfangshuo** [comment]
我找到了 感谢你的提示
