### ISSUE TITLE
evaluation = dict(interval=1, metric='accuracy')

### ISSUE THREAD

**Issue by dugudongfangshuo** [open-mmlab/mmclassification#445]
你好 问一下metic 除了accuracy 还有其他的吗 ，具体的字段名称和支持的所有类型 我看文档没有仔细说明呀
比如文档里说有：
METRICS：Items to be evaluated on the results, like accuracy, precision, recall, etc.
怎么能用like 其他的评估指标能都列举明白吗

**Comment by Ezra-Yu** [comment]
不同数据集会有不同，基本的已经实现评估标准有以下几种：
"accuracy", "precision", "recall", "f1_score", "support" for single  label dataset, and "mAP", "CP", "CR", "CF1", "OP", "OR", "OF1" for multi-label dataset.

**Comment by mzr1996** [comment]
Please use the issue template, and use English or Chinese & English to open issues, so that your question can help more people.

The available metrics are defined in the `evaluate` function of dataset class, usually, the `evaluate` function of single-label datasets is defined in `BaseDataset`: https://github.com/open-mmlab/mmclassification/blob/617932dd59297582d0e9be6a16f1ec42d57f3ecf/mmcls/datasets/base_dataset.py#L117-L144
And the `evaluate` function of multi-label datasets is defined in `MultiLabelDataset`:
https://github.com/open-mmlab/mmclassification/blob/617932dd59297582d0e9be6a16f1ec42d57f3ecf/mmcls/datasets/multi_label.py#L26-L60

**Comment by dugudongfangshuo** [comment]
thanks  多谢
