### ISSUE TITLE
mobilenetV2测试imagenet(val),得到的准确率只有0.02

### ISSUE THREAD

**Issue by SuanTangYu** [open-mmlab/mmclassification#68]
你好，我使用下面的指令对imagenet 的测试集进行测试，却得不到官方的结果
尝试1：使用pycharm 运行tools/test.py , 加上这个 configs/imagenet/mobilenet_v2_b32x8.py checkpoint/mobilenet_v2_batch256_20200708-3b2dc3af.pth
尝试2：
python tools/test.py configs/imagenet/mobilenet_v2_b32x8.py checkpoint/mobilenet_v2_batch256_20200708-3b2dc3af.pth
尝试3：
bash ./tools/dist_test.sh  configs/imagenet/mobilenet_v2_b32x8.py checkpoint/mobilenet_v2_batch256_20200708-3b2dc3af.pth 1

得到的准确率都是0.02，与官方结果相差甚远

**Comment by xiaojieli0903** [comment]
Hello @SuanTangYu, Thanks for reporting the issue. But I have tested the model downloaded from the model zoo using the second and the third way you provided. And all the test results are consistent with the accuracies reported in https://github.com/open-mmlab/mmclassification/blob/master/docs/model_zoo.md. 
I'm afraid your issue is caused by other reasons. Are there any errors or warnings when you test the models? 
What changes did you make to the code？

**Comment by SuanTangYu** [comment]
你好，我已经找到原因了，是因为我的测试数据集的标签对不上号，重新下载了一个新的val.txt之后就没问题了，实在是打扰了
