### ISSUE TITLE
about TensorboardLoggerHook or NeptuneLoggerHook have some problems.

### ISSUE THREAD

**Issue by NeekHua** [open-mmlab/mmclassification#704]
I would like to see the training pictures used during the training,and I found this frame  can use mmcv/runner/hooks/logger/neptune or  mmcv/runner/hooks/logger/tensorboard  show training details.But not show train picture.
What should I change to solve my problem?
Looking forward to a reply

**Comment by teamwong111** [comment]
If you mean the intermediate results (pictures) during training, I'm sorry that mmcv doesn't support it yet, because `runner.log_buffer` does not store intermediate results. If we modify this, all downstream repos need to adapt it, which is too hard. But we will support this feature in the 2022 new design.

**Comment by NeekHua** [comment]
@teamwong111 ok,I got it .Thanks for your help!
