### ISSUE TITLE
Type ClassBalancedDataset have some problems

### ISSUE THREAD

**Issue by NeekHua** [open-mmlab/mmclassification#747]
Problem one : what is the param oversanple_thr means? I find default is 0.001,and repeat_factors of all class is 1,I think maybe it's doesn't work.
Problem two : If I use ClassBalancedDataset in my config ,use vis_pipeline.py It's wrong ,Whether vis_pipeline.py don't support ClassBalancedDataset?

Any reply for me will be exciting~

**Comment by NeekHua** [comment]
About Problem one ,I think I should have answer.
oversample_thr is threshold ,if your single class  in all class proporation lower repeat_factors,ClassBalancedDataset is work ,or else,it doesn't work.0.001 for my dataset is so small.

**Comment by mzr1996** [comment]
Hello, here is the docstring of the argument `oversample_thr`:
```
        oversample_thr (float): frequency threshold below which data is
            repeated. For categories with `f_c` >= `oversample_thr`, there is
            no oversampling. For categories with `f_c` < `oversample_thr`, the
            degree of oversampling following the square-root inverse frequency
            heuristic above.
```

As for the second question, yes. Because the `ClassBalancedDataset` is a wrapper of dataset, and therefore, the `vis_pipeline.py` cannot access some attributes of the dataset. If you just want to preview the pipeline's effect, just remove the wrapper.

**Comment by NeekHua** [comment]
@mzr1996 thks your reply，I see
