### ISSUE TITLE
The difference between init_cfg and load_from

### ISSUE THREAD

**Issue by EstherJinyan** [open-mmlab/mmclassification#770]
Hi,Could you please tell me the difference between setting **pretrained** in the model and setting **load_from** ?
model = dict( 
    backbone=dict(
        init_cfg=dict(
            type='Pretrained',
            checkpoint='../data/pretrained/resnet50_8xb32_in1k_20210831-ea4938fc.pth',
            prefix='backbone',
        )),)
load_from = '../data/pretrained/resnet50_8xb32_in1k_20210831-ea4938fc.pth'
Thanks.

**Comment by EstherJinyan** [comment]
thanks, I have two more questions.

1.Why is init_cfg a dict structure in some models and a list structure? For example, in resnet, it is written as follows, 
model = dict(
backbone=dict(
init_cfg=dict(
type='Pretrained',
checkpoint='../data/pretrained/resnet50_8xb32_in1k_20210831-ea4938fc.pth',
prefix='backbone',
)),)
but in t2tnet, it needs to be written like this：
model = dict(
    backbone=dict(
        init_cfg=[
            dict(type='Pretrained',
            checkpoint='../data/pretrained/t2t-vit-t-19_8xb64_in1k_20211214-7f5e3aaf.pth',
            prefix='backbone')]
    )

2.When the model structure is not completely consistent, such as inconsistent heads, will **load_from** not load the weights?Will it still load part of it?

**Comment by Ezra-Yu** [comment]
For Q1:
you can refer to [mmcv init_cfg doc](https://mmdetection.readthedocs.io/en/latest/tutorials/init_cfg.html).
1. for tnt, a dict init_cfg is OK and more recommended:
```
backbone=dict(
init_cfg=dict(type='Pretrained',
checkpoint='../data/pretrained/t2t-vit-t-19_8xb64_in1k_20211214-7f5e3aaf.pth',
prefix='backbone'))
```
2. `list` data  structure `init_cfg` is usually used in training from scratch, such as using kaiming init in conv, uniform in linear, and zero the bais of BN.......


For Q2:
`load_from` will load where the key name is consistent. Conflicting parts will be skipped and print warning.

**Comment by pvmilk** [comment]
I might be late for the show. My questions are:

- If there are both "load_from" and "init_cfg" in my configuration which will be loaded first?
- How either of the two,  "load_from" and "init_cfg", effect the submodules that are 'pure-pytorch' (not a sub-class of mmengine.BaseModule)?

I am asking this as I have some submodules in my model that is "pure-pytorch" and I would like to load the weight to perform inference.

Thank yo in advanced.

**Comment by pvmilk** [comment]
> 
> * If there are both "load_from" and "init_cfg" in my configuration which will be loaded first?
>

Please correct me if I am wrong.
Base on code in mmengine.Runner, it seems "init_cfg" will be called first and then "load_from" during training.

https://github.com/open-mmlab/mmengine/blob/39ed23fae87267de8ef044a94a597a6904fe7f85/mmengine/runner/runner.py#L1746-L1766

**Comment by pvmilk** [comment]
>
> * How either of the two,  "load_from" and "init_cfg", effect the submodules that are 'pure-pytorch' (not a sub-class of mmengine.BaseModule)?
> 
For the second question, let me try to answer it myself (Please correct me if I am wrong).

"init_cfg" will only be called through mmengine.BaseModule.init_weights().
Therefore, any submodule that are "pure-pytorch" will need to implement this function, in order to be initialized.
So, for "pure-pytorch" submodule, if initialization is not called from the first place, weight from the file will not be loaded.
https://mmengine.readthedocs.io/en/latest/advanced_tutorials/initialize.html (section: Customize the initialization method)


However, "load_from" is something else.
It simply copied the state_dict from the checkpoint to the every module that is torch.nn.module.
Nothing to do with sub-class of mmengine.BaseModule

https://github.com/open-mmlab/mmengine/blob/39ed23fae87267de8ef044a94a597a6904fe7f85/mmengine/runner/checkpoint.py#L585-L608
