### ISSUE TITLE
About the 'single_gpu_test' api

### ISSUE THREAD

**Issue by XingtongGe** [open-mmlab/mmclassification#798]
Hi, I wonder if the 'single_gpu_test' api in mmcv>engine>test.py is called when val_step in training instead of the 'single_gpu_test' api in mmcls>apis>test.py ?
If so, what should I do so that the test api in mmcls can be called when training?

**Comment by Ezra-Yu** [comment]
I guess that you want to know about the evaluation function.

MMClassification call the [`mmcv.runner.hooks.EvalHook`](https://github.com/open-mmlab/mmcv/blob/4fb59b9830a880e5962e6cf43b9c57738867f712/mmcv/runner/hooks/evaluation.py#L16) in training  instead of `val_single_gpu_test` in testing to calculate the test metrics. The  val_step only uesd to **caculate the loss** of val dataset, refer to the [work-flow docs](https://mmclassification.readthedocs.io/en/latest/tutorials/runtime.html#customize-workflow).

MMClassification register EvalHook in these [lines](https://github.com/open-mmlab/mmclassification/blob/6beac5060f0c1d57141642dba77c19c9ed6b3873/mmcls/apis/train.py#L211-L216), the config line dict is [here](https://github.com/open-mmlab/mmclassification/blob/6beac5060f0c1d57141642dba77c19c9ed6b3873/configs/_base_/datasets/imagenet_bs64_mixer_224.py#L48).

**Comment by Ezra-Yu** [comment]
Did the answer solve your question?

I am going to close this issue.

**Comment by XingtongGe** [comment]
Yes, thanks for your reply!
